# Generated by Django 4.2.6 on 2023-11-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detenido',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
