# Generated by Django 4.2.6 on 2023-11-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_detenido_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detenido',
            name='dni',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detenido',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
